### PR TITLE
fix: use ethermint KeyCommands

### PR DESCRIPTION
**Pull request by JoowonYun**
## Effects

- [ ] Soft update
- [ ] Breaking change
- [ ] Chain fork related

## Checklist

- [ ] Backward compatible?
- [ ] Test enough in your local environment?
- [ ] Add related test cases?

### CODE REVIEW

**Review by caramis — COMMENTED** [review]
Do we need to fork the Cosmos SDK to use xplaclient for ethereum keys?

**Comment by JoowonYun** [comment]
> Do we need to fork the Cosmos SDK to use xplaclient for ethereum keys?

Does it mean that the file is unnecessary? `github.com/xpladev/xpla/client/keys.go`

**Comment by caramis** [comment]
No, I mean can we use xpla/client/keys.go and use "ethermintclient" inside "keys.go".
And "github.com/xpladev/xpla/client/keys.go" is unnecessary??

**Review by caramis — APPROVED** [review]
LGTM

**Pull request merged**
